### PR TITLE
debug-meta-lang: make (require sugar/debug) unnecessary

### PR DESCRIPTION
**Pull request by AlexKnauth**
and make it hygienic

### CODE REVIEW

**Comment by AlexKnauth** [comment]
This is failing on HEAD:
https://travis-ci.org/mbutterick/sugar/jobs/72652359

**Comment by AlexKnauth** [comment]
Oh, but `master` is already failing on HEAD with the same error.

**Comment by mbutterick** [comment]
Everything fails on HEAD these days.

**Comment by AlexKnauth** [comment]
This does work with both the old and the new expander though.

**Comment by mbutterick** [comment]
Progress.

**Pull request merged**
