### PR TITLE
This fixes sugar and pollen to work with the new expander. I believe that it will work on 6.2 as well.

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by mbutterick** [comment]
Thank you, but Travis says it’s still broken on HEAD —

https://travis-ci.org/mbutterick/sugar/builds/75661137

**Comment by mbutterick** [comment]
(It’s not showing up as an error here because I’ve configured Travis to silence errors on HEAD)

**Comment by samth** [comment]
Ok, I fixed that file's problems as well (plus an unrelated error that now appears on HEAD).

**Comment by samth** [comment]
And now it works everywhere.

**Comment by mbutterick** [comment]
OK, thank you. To infinity and beyond.

**Comment by mbutterick** [comment]
Pollen’s going to [need some more work](https://travis-ci.org/mbutterick/pollen/jobs/75551739) to be compatible with the new expander due to non-hygienic (or just sloppy) macrology. But this is a good start, thanks again.

**Pull request merged**
